FROM python:3.12
EXPOSE 8000
ENV DATABASE_URL="mongodb://cvh-backend:27017"
WORKDIR /app
COPY . /app
RUN pip install --no-cache-dir -e ".[dev]"
RUN pip install uvicorn
RUN useradd app
USER app
WORKDIR /app/src
CMD ["uvicorn", "dcc2cvh.cvh.api.main:app", "--host", "0.0.0.0", "--port", "8000"]
